import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { Web3Provider } from "../context/Web3Context"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3Provider>
      <Script
          src="https://checkout.razorpay.com/v1/checkout.js"
          strategy="beforeInteractive"
        />
        {children}
        </Web3Provider>
      </body>
    </html>
  );
}
