/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Billboard(props) {
  const { nodes, materials } = useGLTF("./models/billboard.glb");
  return (
    <group
      {...props}
      dispose={null}
      position={[48.9, 0, 0]}
      rotation={[0, Math.PI / -2, 0]}
      scale={[2, 2, 2]}
    >
      <group position={[0, 4.486, 0]} scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001.geometry}
          material={materials.dbl_Layer0_001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_1.geometry}
          material={materials.dbl_Layer0_002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_2.geometry}
          material={materials.dbl_Layer0_003}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_3.geometry}
          material={materials.dbl_Layer0_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_4.geometry}
          material={materials.dbl_Layer0_005}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_5.geometry}
          material={materials.dbl_Layer0_006}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_6.geometry}
          material={materials.dbl_Layer0_007}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_7.geometry}
          material={materials.dbl_Layer0_008}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/billboard.glb");
