/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Open24(props) {
  const { nodes, materials } = useGLTF('./models/open24.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 3.578, 2.426]} rotation={[-0.042, 0, 0]} scale={0.082}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sign_neon_24h_1.geometry}
          material={materials.StingrayPBS8SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sign_neon_24h_2.geometry}
          material={materials.StingrayPBS7SG}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/open24.glb')
